<a href="https://colab.research.google.com/github/Auvarmf/Riset-MBKM-CNN2023/blob/main/Part_4_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [64]:
# List
[1, 2, 3] * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

# Numerical Python (Numpy)

In [65]:
import numpy as np

In [66]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [67]:
a * 3

array([3, 6, 9])

# Math Functions

In [68]:
np.sum(a)

6

In [69]:
np.mean(a)

2.0

In [70]:
np.std(a)

0.816496580927726

In [71]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

# Arange, linspace, longspace

In [72]:
np.arange(0, 5, 1.5)

array([0. , 1.5, 3. , 4.5])

In [73]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [74]:
np.logspace(-3, 3, 7)

array([1.e-03, 1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02, 1.e+03])

# Random

In [75]:
np.random.rand(3, 2)

array([[0.2222228 , 0.9195309 ],
       [0.3882888 , 0.43976767],
       [0.516134  , 0.7454487 ]])

# Controlled Randomness

In [76]:
state = np.random.RandomState(42)
state.rand(3)

array([0.37454012, 0.95071431, 0.73199394])